-- MySQL Script generated by MySQL Workbench
-- Wed Oct  4 13:25:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pacainDB
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `pacainDB` ;
-- CREATE SCHEMA IF NOT EXISTS `pacainDB` DEFAULT CHARACTER SET utf8 ;
USE `pacainDB` ;

-- -----------------------------------------------------
-- Table `pacainDB`.`indirizzo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacainDB`.`indirizzo` ;

CREATE TABLE IF NOT EXISTS `pacainDB`.`indirizzo` (
  `nome` VARCHAR(45) NOT NULL,
  `città` VARCHAR(45) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacainDB`.`padrone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacainDB`.`padrone` ;

CREATE TABLE IF NOT EXISTS `pacainDB`.`padrone` (
  `cf` VARCHAR(16) NOT NULL,
  `indirizzo` VARCHAR(45) NULL,
  PRIMARY KEY (`cf`),
  CONSTRAINT `indirizzo`
    FOREIGN KEY (`indirizzo`)
    REFERENCES `pacainDB`.`indirizzo` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `indirizzo_idx` ON `pacainDB`.`padrone` (`indirizzo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `pacainDB`.`cane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacainDB`.`cane` ;

CREATE TABLE IF NOT EXISTS `pacainDB`.`cane` (
  `matricola` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`matricola`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pacainDB`.`padronanza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pacainDB`.`padronanza` ;

CREATE TABLE IF NOT EXISTS `pacainDB`.`padronanza` (
  `padrone` VARCHAR(16) NOT NULL,
  `cane` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`padrone`, `cane`),
  CONSTRAINT `padrone`
    FOREIGN KEY (`padrone`)
    REFERENCES `pacainDB`.`padrone` (`cf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cane`
    FOREIGN KEY (`cane`)
    REFERENCES `pacainDB`.`cane` (`matricola`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `cane_idx` ON `pacainDB`.`padronanza` (`cane` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
